### ISSUE TITLE
Error in demo install

### ISSUE THREAD

**Issue by fsainovich** [wireapp/wire-docs#21]
root@kubenode01:~/wire-server-deploy/wire-server# helm upgrade --install wire-server wire/wire-server -f values.yaml -f secrets.yaml --wait
Release "wire-server" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec): unknown field "podManagementPolicy" in io.k8s.api.core.v1.PodSpec

root@kubenode01:~/wire-server-deploy/wire-server# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

root@kubenode01:~/wire-server-deploy/wire-server# helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

**Comment by jschaul** [comment]
The code and documentation used helm versions 2.x (v2.11 / v2.14 are known to work). Helm 3.x is not yet supported.

**Comment by jschaul** [comment]
(but thanks for reporting! We'll try to fix that soon.)

**Comment by arianvp** [comment]
This is the same issue as https://github.com/wireapp/wire-server-deploy/issues/167

**Comment by lucendio** [comment]
Fixed with https://github.com/wireapp/wire-server-deploy/commit/a1662b763a388ec6025bd7d375b96497ffd000bb
