### ISSUE TITLE
Copyright date is wrong (2021)

### ISSUE THREAD

**Issue by arthurwolf** [wireapp/wire-docs#254]
Alan noticed that the date at the bottom of the docs.wire.com pages is wrong:

![Screenshot from 2022-01-20 18-22-34](https://user-images.githubusercontent.com/108821/150389710-a0a0dc2e-d4a9-4dab-ad3d-bbf23d1ddab6.png)

I did a search for this in the repo but can't find it:

![Screenshot from 2022-01-20 18-23-10](https://user-images.githubusercontent.com/108821/150389823-ca7abb1b-3fa4-44a0-b31c-eab01bca011c.png)

Shouldn't this use the server's local time? If it does, why is it wrong, and if it does not, where do we change it? Anyone knows?

**Comment by mdimjasevic** [comment]
Copyright cannot be dependent on the current time. Assuming we've made changes in 2022, the copyright should be dated 2022; if the last change was in 2021, it stays there.

I assume where it is defined is in `src/conf.py` on line 21:

```python
copyright = '2021, Wire'
```

**Comment by arthurwolf** [comment]
So we should manually change it each year is the idea?

This is actively maintained, it's edited often enough that for any given year, within the first few days of it, the manual edit should be done. 

The upside of automating it is we won't forget. 

I'm not sure what the downside is? 

As I can see/imagine, only would matter in the case Wire is doing pretty bad/going under (causing no more maintenance of the e docs), in which case, would it really matter that the copyright isn't the right date at that point? I'm really asking, I don't know. Also, are there other scenarios where this would happen/matter?

**Comment by mdimjasevic** [comment]
Sure, this can be automated! I was just trying to raise awareness that copyright cannot be claimed for a year when there was no change, but I see you're aware of that. My apologies for crashing this thread, I see you know stuff on copyright!

**Comment by arthurwolf** [comment]
Thanks for the vigilance, this is important stuff, so no crashing/apologies here.
