### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by fisx** [wireapp/wire-docs#26]
```
$ make
[...]
/mnt/src/how-to/api-client-perspective/index.rst: WARNING: document isn't included in any toctree
```

@jschaul

**Comment by jschaul** [comment]
I know. See also https://github.com/zinfra/backend-issues/issues/838#issuecomment-545402795 - more API documentation pages would need to be ported, and then an index file created that describes what is documented and what is not (and may be in the future).

**Comment by tiago-loureiro** [comment]
How about https://github.com/wireapp/wire-docs/pull/37

**Comment by fisx** [comment]
I patched your PR a little.  :)

**Comment by fisx** [comment]
(but thanks!  should have done that to begin with, instead of opening an issue.)
