### ISSUE TITLE
Declarative Diagrams with Mermaid

### ISSUE THREAD

**Issue by arthurwolf** [wireapp/wire-docs#280]
GitHub recently announced they support Mermaid diagrams: https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

@rohan-wire in a recent call asked if that's something we could use in docs.wire.com

I think it'd make sense, and where applicable it'd be preferable to the current method (use draw.io, generate/render files, commit them along with their source XML file, etc.)

I looked into it, and there's a module for mermaid support in sphinx:

https://github.com/mgaitan/sphinxcontrib-mermaid

Supports rendering even for non-html output, external mermaid files, etc...
Installation looks straightforward.

Any opinions on enabling this and experimenting with using it for simple diagrams moving forward?

**Comment by jschaul** [comment]
Mermaid is already supported, see the README in https://github.com/wireapp/wire-docs/blob/379172a5dbc745a13d7042897ac0938a20764017/diagrams/README.md#diagrams-with-kroki--mermaid and just create a 

```
.. kroki::
   :type: mermaid
   :caption: Diagram
   
   ...
```

block anywhere in a file.
