### ISSUE TITLE
Helm version error

### ISSUE THREAD

**Issue by fanpero87** [wireapp/wire-docs#94]
Hello,
I was trying to follow the guide to create a wire-server (Demo) and I got problems after installing Helm.
`wire@wire:~/wire-server-deploy/wire-server$ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
`
I got problems running:
helm upgrade --install fake-aws wire/fake-aws --wait
helm upgrade --install wire-server wire/wire-server -f values.yaml -f secrets.yaml --wait

Those two pods doesn't run with any v2.X version of Helm. Also, If I go up to: 

`wire@wire:~/Downloads$ helm version
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/wire/.kube/config
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}`

I can run the helm upgrade commands, but at the end the process fails.

What version of Helm is the best one to use on this guide?

Thanks.

**Comment by lucendio** [comment]
> What version of Helm is the best one to use on this guide?

At the moment, that would be `v3.1.1` together with `v1.14.2`. Please note that the latter is legacy, and we are currently working on getting everything compatible with a recent LTS version of K8s.

Thank you pointing this out. I created https://github.com/wireapp/wire-docs/pull/95 to address this.
